package com.duabiskuttelur.service;

import com.duabiskuttelur.model.AnalysisResponse;
import com.duabiskuttelur.model.FoodItem;
import com.lowagie.text.Chunk;
import com.lowagie.text.Document;
import com.lowagie.text.Element;
import com.lowagie.text.Font;
import com.lowagie.text.FontFactory;
import com.lowagie.text.PageSize;
import com.lowagie.text.Paragraph;
import com.lowagie.text.Phrase;
import com.lowagie.text.pdf.PdfPCell;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfWriter;
import org.springframework.stereotype.Service;

import java.awt.Color;
import java.io.ByteArrayOutputStream;
import java.time.Instant;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.Locale;
import java.util.Map;

/** Renders a saved meal report as a clean, shareable PDF. */
@Service
public class PdfReportService {

    private static final Color BRAND = new Color(0x16, 0xA3, 0x4A);
    private static final Color MUTED = new Color(0x64, 0x74, 0x8B);
    private static final Map<String, Color> GRADE_COLORS = Map.of(
            "A+", new Color(0x16, 0xA3, 0x4A),
            "A", new Color(0x22, 0xC5, 0x5E),
            "B", new Color(0xCA, 0x8A, 0x04),
            "C", new Color(0xEA, 0x58, 0x0C),
            "D", new Color(0xDC, 0x26, 0x26));

    private final Font titleFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 20, Color.BLACK);
    private final Font sectionFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 12, Color.BLACK);
    private final Font bodyFont = FontFactory.getFont(FontFactory.HELVETICA, 10, Color.BLACK);
    private final Font mutedFont = FontFactory.getFont(FontFactory.HELVETICA, 9, MUTED);
    private final Font headerFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 9, Color.WHITE);

    public byte[] render(AnalysisResponse result, Instant createdAt) {
        try {
            Document doc = new Document(PageSize.A4, 40, 40, 50, 40);
            ByteArrayOutputStream out = new ByteArrayOutputStream();
            PdfWriter.getInstance(doc, out);
            doc.open();

            doc.add(title());
            doc.add(subtitle(createdAt));
            doc.add(Chunk.NEWLINE);
            doc.add(scoreLine(result));
            doc.add(Chunk.NEWLINE);
            doc.add(sectionHeading("Totals"));
            doc.add(totalsTable(result));
            doc.add(Chunk.NEWLINE);
            doc.add(sectionHeading("What's on the plate"));
            doc.add(foodsTable(result.foods()));

            addFeedbackSection(doc, "Highlights", result.highlights());
            addFeedbackSection(doc, "Concerns", result.concerns());
            addFeedbackSection(doc, "Next time", result.suggestions());

            if (result.encouragement() != null && !result.encouragement().isBlank()) {
                doc.add(Chunk.NEWLINE);
                Paragraph enc = new Paragraph(result.encouragement(), bodyFont);
                enc.setSpacingBefore(6);
                doc.add(enc);
            }

            Paragraph footer = new Paragraph("Generated by DuaBiskutTelur", mutedFont);
            footer.setSpacingBefore(24);
            footer.setAlignment(Element.ALIGN_CENTER);
            doc.add(footer);

            doc.close();
            return out.toByteArray();
        } catch (Exception e) {
            throw new RuntimeException("Failed to render PDF report", e);
        }
    }

    private Paragraph title() {
        Paragraph p = new Paragraph("DuaBiskutTelur — Meal Report", titleFont);
        p.setAlignment(Element.ALIGN_CENTER);
        return p;
    }

    private Paragraph subtitle(Instant createdAt) {
        String formatted = DateTimeFormatter.ofPattern("d MMM yyyy, h:mm a", Locale.ENGLISH)
                .withZone(ZoneId.systemDefault())
                .format(createdAt);
        Paragraph p = new Paragraph(formatted, mutedFont);
        p.setAlignment(Element.ALIGN_CENTER);
        p.setSpacingBefore(4);
        return p;
    }

    private Paragraph scoreLine(AnalysisResponse result) {
        Color gradeColor = GRADE_COLORS.getOrDefault(result.grade(), Color.BLACK);
        Font gradeFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 28, gradeColor);
        Font scoreFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 16, Color.BLACK);

        Paragraph p = new Paragraph();
        p.setAlignment(Element.ALIGN_CENTER);
        p.add(new Chunk("Grade " + result.grade() + "   ", gradeFont));
        p.add(new Chunk("(" + result.score() + " / 100)", scoreFont));
        return p;
    }

    private Paragraph sectionHeading(String text) {
        Paragraph p = new Paragraph(text, sectionFont);
        p.setSpacingBefore(10);
        p.setSpacingAfter(6);
        return p;
    }

    private PdfPTable totalsTable(AnalysisResponse result) {
        var t = result.totals();
        String[][] rows = {
                {"Calories", Math.round(t.calories()) + " kcal"},
                {"Protein", t.protein() + " g"},
                {"Carbs", t.carbs() + " g"},
                {"Fat", t.fat() + " g"},
                {"Fiber", t.fiber() + " g"},
                {"Sugar", t.sugar() + " g"},
                {"Sodium", Math.round(t.sodium()) + " mg"},
        };
        PdfPTable table = new PdfPTable(new float[]{1, 1, 1, 1});
        table.setWidthPercentage(100);
        for (String[] row : rows) {
            table.addCell(labelCell(row[0]));
            table.addCell(valueCell(row[1]));
        }
        return table;
    }

    private PdfPTable foodsTable(List<FoodItem> foods) {
        PdfPTable table = new PdfPTable(new float[]{3, 1.4f, 1, 1, 1});
        table.setWidthPercentage(100);
        for (String h : new String[]{"Food", "Portion", "Calories", "Protein", "Source"}) {
            PdfPCell cell = new PdfPCell(new Phrase(h, headerFont));
            cell.setBackgroundColor(BRAND);
            cell.setPadding(5);
            table.addCell(cell);
        }
        for (FoodItem f : foods) {
            table.addCell(valueCell(f.name()));
            table.addCell(valueCell(f.estimatedPortion()));
            table.addCell(valueCell(Math.round(f.calories()) + " kcal"));
            table.addCell(valueCell(f.protein() + " g"));
            table.addCell(valueCell(f.source()));
        }
        return table;
    }

    private void addFeedbackSection(Document doc, String title, List<String> items) throws Exception {
        if (items == null || items.isEmpty()) return;
        doc.add(sectionHeading(title));
        for (String item : items) {
            Paragraph p = new Paragraph("•  " + item, bodyFont);
            p.setSpacingAfter(2);
            doc.add(p);
        }
    }

    private PdfPCell labelCell(String text) {
        PdfPCell cell = new PdfPCell(new Phrase(text, mutedFont));
        cell.setPadding(5);
        cell.setBorderColor(Color.LIGHT_GRAY);
        return cell;
    }

    private PdfPCell valueCell(String text) {
        PdfPCell cell = new PdfPCell(new Phrase(text, bodyFont));
        cell.setPadding(5);
        cell.setBorderColor(Color.LIGHT_GRAY);
        return cell;
    }
}
