package com.duabiskuttelur.service;

import com.duabiskuttelur.model.TrendDay;
import com.duabiskuttelur.model.TrendReportResponse;
import com.duabiskuttelur.model.TrendTotals;
import com.lowagie.text.Chunk;
import com.lowagie.text.Document;
import com.lowagie.text.Element;
import com.lowagie.text.Font;
import com.lowagie.text.FontFactory;
import com.lowagie.text.PageSize;
import com.lowagie.text.Paragraph;
import com.lowagie.text.Phrase;
import com.lowagie.text.pdf.PdfPCell;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfWriter;
import org.springframework.stereotype.Service;

import java.awt.Color;
import java.io.ByteArrayOutputStream;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.Map;

/**
 * Renders a trend report as a PDF, for taking to a doctor or a coach.
 *
 * <p>A new template rather than a new capability: OpenPDF and the visual
 * language both come from {@link PdfReportService}, which already exports a
 * single meal.
 *
 * <h2>Why this document is in English</h2>
 * The base-14 PDF fonts these reports use are Cp1252-encoded, so they can
 * represent Latin text and nothing else. A Chinese paragraph passed through
 * Helvetica does not fail loudly -- it silently drops the glyphs and leaves an
 * export that looks like it worked and is blank where the writing should be.
 * Embedding a CJK face would add roughly ten megabytes to the image for a
 * secondary feature, so the export is English until that trade is worth making,
 * and the caller asks the narrator for English prose to match rather than
 * shipping a paragraph the document cannot draw.
 */
@Service
public class TrendPdfService {

    private static final Color BRAND = new Color(0x16, 0xA3, 0x4A);
    private static final Color MUTED = new Color(0x64, 0x74, 0x8B);
    private static final Color OVER = new Color(0xF5, 0x9E, 0x0B);
    private static final Color RULE = new Color(0xE2, 0xE8, 0xF0);

    private static final DateTimeFormatter RANGE = DateTimeFormatter.ofPattern("d MMM yyyy", Locale.ENGLISH);
    private static final DateTimeFormatter DAY = DateTimeFormatter.ofPattern("EEE d MMM", Locale.ENGLISH);

    private final Font titleFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 20, Color.BLACK);
    private final Font sectionFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 12, Color.BLACK);
    private final Font bodyFont = FontFactory.getFont(FontFactory.HELVETICA, 10, Color.BLACK);
    private final Font mutedFont = FontFactory.getFont(FontFactory.HELVETICA, 9, MUTED);
    private final Font headerFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 9, Color.WHITE);
    private final Font bigFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 18, Color.BLACK);

    public byte[] render(TrendReportResponse report) {
        try {
            Document doc = new Document(PageSize.A4, 40, 40, 50, 40);
            ByteArrayOutputStream out = new ByteArrayOutputStream();
            PdfWriter.getInstance(doc, out);
            doc.open();

            doc.add(title(report));
            doc.add(subtitle(report));

            doc.add(sectionHeading("Summary"));
            doc.add(headlineTable(report));

            if (report.narrative() != null && !report.narrative().isBlank()) {
                Paragraph p = new Paragraph(report.narrative(), bodyFont);
                p.setSpacingBefore(10);
                doc.add(p);
            }

            doc.add(sectionHeading("Habits"));
            doc.add(habitsTable(report.totals()));

            doc.add(sectionHeading("Daily calories"));
            doc.add(daysTable(report));

            if (hasAnyGrade(report.gradeMix())) {
                doc.add(sectionHeading("Grade mix"));
                doc.add(gradeTable(report.gradeMix()));
            }

            Paragraph footer = new Paragraph(
                    "Generated by DuaBiskutTelur. Figures are computed from your logged meals.", mutedFont);
            footer.setSpacingBefore(18);
            doc.add(footer);

            doc.close();
            return out.toByteArray();
        } catch (Exception e) {
            throw new IllegalStateException("Could not render the trend report PDF", e);
        }
    }

    /** A filename that sorts and says what it is without being opened. */
    public static String filenameFor(TrendReportResponse report) {
        return "duabiskuttelur-" + report.period() + "-" + report.to() + ".pdf";
    }

    private Paragraph title(TrendReportResponse report) {
        String what = "month".equals(report.period()) ? "Monthly Report" : "Weekly Report";
        Paragraph p = new Paragraph("DuaBiskutTelur - " + what, titleFont);
        p.setSpacingAfter(2);
        return p;
    }

    private Paragraph subtitle(TrendReportResponse report) {
        String range = report.from().format(RANGE) + " to " + report.to().format(RANGE);
        String coverage = report.totals().daysLogged() + " of " + report.daysInWindow() + " days logged";
        Paragraph p = new Paragraph(range + "  |  " + coverage, mutedFont);
        p.setSpacingAfter(14);
        return p;
    }

    private Paragraph sectionHeading(String text) {
        Paragraph p = new Paragraph(text, sectionFont);
        p.setSpacingBefore(14);
        p.setSpacingAfter(6);
        return p;
    }

    /**
     * The headline figures, each with its change against the previous period.
     *
     * <p>Only the ones the report actually computed. A metric the server
     * withheld as "not enough to say" is left out of the document entirely
     * rather than printed as a zero -- a PDF outlives the screen it came from,
     * and a zero in it will be read as a measurement long after the context is
     * gone.
     */
    private PdfPTable headlineTable(TrendReportResponse report) {
        TrendTotals t = report.totals();
        TrendTotals p = report.previous();
        List<String[]> rows = new ArrayList<>();
        addRow(rows, "Average daily calories", t.avgDailyCalories(), p == null ? null : p.avgDailyCalories(), "kcal");
        addRow(rows, "Average grade", t.avgGrade(), p == null ? null : p.avgGrade());
        addRow(rows, "Average daily protein", t.avgDailyProtein(), p == null ? null : p.avgDailyProtein(), "g");
        addRow(rows, "Meals logged", t.mealCount(), p == null ? null : p.mealCount(), "");

        PdfPTable table = new PdfPTable(new float[]{2.2f, 1, 1.4f});
        table.setWidthPercentage(100);
        header(table, "Metric", "This " + report.period(), "Change");
        for (String[] row : rows) {
            table.addCell(labelCell(row[0]));
            table.addCell(valueCell(row[1]));
            table.addCell(valueCell(row[2]));
        }
        return table;
    }

    private static void addRow(List<String[]> rows, String label, Integer now, Integer before, String unit) {
        if (now == null) {
            return;
        }
        String value = now + (unit.isEmpty() ? "" : " " + unit);
        String change = before == null ? "-" : signed(now - before) + (unit.isEmpty() ? "" : " " + unit);
        rows.add(new String[]{label, value, change});
    }

    private static void addRow(List<String[]> rows, String label, String now, String before) {
        if (now == null) {
            return;
        }
        rows.add(new String[]{label, now, before == null || before.equals(now) ? "-" : "was " + before});
    }

    private static String signed(int delta) {
        return delta > 0 ? "+" + delta : String.valueOf(delta);
    }

    private PdfPTable habitsTable(TrendTotals t) {
        List<String[]> rows = new ArrayList<>();
        if (t.vegetableServings() != null) {
            rows.add(new String[]{"Vegetable servings", String.valueOf(t.vegetableServings())});
        }
        if (t.fruitDays() != null) {
            rows.add(new String[]{"Days with fruit", t.fruitDays() + " of " + t.daysLogged()});
        }
        if (t.avgDailyWaterMl() != null) {
            rows.add(new String[]{"Average daily water",
                    String.format(Locale.ENGLISH, "%.1f L", t.avgDailyWaterMl() / 1000.0)
                            + " (" + t.waterDaysOnTarget() + " days on target)"});
        }
        if (t.workoutsDone() != null) {
            rows.add(new String[]{"Workouts completed", t.workoutsDone() + " (" + t.workoutMinutes() + " min)"});
        }
        if (t.latestWeightKg() != null) {
            String weight = String.format(Locale.ENGLISH, "%.1f kg", t.latestWeightKg());
            if (t.weightChangeKg() != null) {
                weight += String.format(Locale.ENGLISH, " (%+.1f over the period)", t.weightChangeKg());
            }
            rows.add(new String[]{"Latest weight", weight});
        }
        if (rows.isEmpty()) {
            rows.add(new String[]{"No habit data", "Nothing recorded in this period"});
        }

        PdfPTable table = new PdfPTable(new float[]{2.2f, 2.4f});
        table.setWidthPercentage(100);
        for (String[] row : rows) {
            table.addCell(labelCell(row[0]));
            table.addCell(valueCell(row[1]));
        }
        return table;
    }

    /**
     * Every day in the window, including the ones with nothing in them.
     *
     * <p>The gaps are the point. A doctor reading this needs to see that
     * Thursday is missing rather than a tidy list of only the good days.
     */
    private PdfPTable daysTable(TrendReportResponse report) {
        PdfPTable table = new PdfPTable(new float[]{1.6f, 1, 1, 1.2f});
        table.setWidthPercentage(100);
        header(table, "Day", "Meals", "Calories", "Vs budget");
        for (TrendDay day : report.days()) {
            table.addCell(valueCell(day.date().format(DAY)));
            if (!day.logged()) {
                table.addCell(valueCell("-"));
                table.addCell(valueCell("not logged"));
                table.addCell(valueCell("-"));
                continue;
            }
            table.addCell(valueCell(String.valueOf(day.mealCount())));
            table.addCell(valueCell(Math.round(day.calories()) + " kcal"));
            if (report.calorieBudget() > 0) {
                int diff = (int) Math.round(day.calories()) - report.calorieBudget();
                PdfPCell cell = new PdfPCell(new Phrase(signed(diff) + " kcal", bodyFont));
                cell.setPadding(5);
                cell.setBorderColor(RULE);
                if (day.overBudget()) {
                    cell.setBackgroundColor(new Color(0xFE, 0xF3, 0xC7));
                }
                table.addCell(cell);
            } else {
                table.addCell(valueCell("-"));
            }
        }
        return table;
    }

    private PdfPTable gradeTable(Map<String, Integer> mix) {
        PdfPTable table = new PdfPTable(mix.size());
        table.setWidthPercentage(100);
        for (String grade : mix.keySet()) {
            PdfPCell cell = new PdfPCell(new Phrase(grade, headerFont));
            cell.setBackgroundColor(BRAND);
            cell.setPadding(5);
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            table.addCell(cell);
        }
        for (Integer count : mix.values()) {
            PdfPCell cell = new PdfPCell(new Phrase(String.valueOf(count), bodyFont));
            cell.setPadding(6);
            cell.setBorderColor(RULE);
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            table.addCell(cell);
        }
        return table;
    }

    private static boolean hasAnyGrade(Map<String, Integer> mix) {
        return mix != null && mix.values().stream().anyMatch(n -> n != null && n > 0);
    }

    private void header(PdfPTable table, String... headings) {
        for (String h : headings) {
            PdfPCell cell = new PdfPCell(new Phrase(h, headerFont));
            cell.setBackgroundColor(BRAND);
            cell.setPadding(5);
            table.addCell(cell);
        }
    }

    private PdfPCell labelCell(String text) {
        PdfPCell cell = new PdfPCell(new Phrase(text, mutedFont));
        cell.setPadding(5);
        cell.setBorderColor(RULE);
        return cell;
    }

    private PdfPCell valueCell(String text) {
        PdfPCell cell = new PdfPCell(new Phrase(text, bodyFont));
        cell.setPadding(5);
        cell.setBorderColor(RULE);
        return cell;
    }
}
