-- A curated composition table for Malaysian dishes, consulted before USDA.
--
-- USDA FoodData Central does not contain nasi lemak, char kway teow, roti canai,
-- cendol or teh tarik. Every one of those currently resolves through
-- usdaSearchTerm to a rough generic ("coconut rice") or falls through to the
-- model's own estimate. For a Malaysia-first product that is a permanent
-- accuracy ceiling, and no amount of prompt work moves it -- the data simply is
-- not in the source being queried.
--
-- Resolution order becomes local -> USDA -> model, and a hit is reported to the
-- UI as source="local", the highest-trust badge: unlike a USDA match it is the
-- actual dish rather than the closest generic equivalent.
--
-- The table ships EMPTY. Rows belong in R__local_food_seed.sql, which is a
-- repeatable Flyway migration precisely so that curating data is a data change
-- rather than a schema change: edit that one file and the next deploy reloads
-- it. See its header for the format and for where the numbers must come from.

CREATE TABLE local_food (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    -- Produced by NutritionCacheService.canonicalize, so this table and the
    -- nutrition cache agree on what counts as the same dish.
    canonical_name VARCHAR(255) NOT NULL,
    display_name VARCHAR(255) NOT NULL,
    -- One typical serving, used by menu scans, which have no plate to measure.
    typical_grams DOUBLE PRECISION NOT NULL,
    calories_per100g DOUBLE PRECISION NOT NULL,
    protein_per100g DOUBLE PRECISION NOT NULL,
    carbs_per100g DOUBLE PRECISION NOT NULL,
    fat_per100g DOUBLE PRECISION NOT NULL,
    fiber_per100g DOUBLE PRECISION NOT NULL,
    sugar_per100g DOUBLE PRECISION NOT NULL,
    sodium_per100g DOUBLE PRECISION NOT NULL,
    food_group VARCHAR(64),
    cooking_method VARCHAR(32),
    -- Provenance, and it is not decoration: it is what makes a wrong number
    -- traceable to the table it was transcribed from. 'MyFCD' | 'HPB' | 'curated'.
    source VARCHAR(64) NOT NULL,
    -- Free-text note on where this row came from -- an edition, a page, a URL.
    -- A composition figure with no citation cannot be checked by the next person.
    provenance VARCHAR(512),
    CONSTRAINT uk_local_food_canonical_name UNIQUE (canonical_name)
);

-- Aliases live in their own indexed table rather than in a comma-separated
-- column on local_food. A delimited column cannot be indexed, so matching
-- "椰浆饭" against it would mean scanning every row -- for every dish of every
-- menu scan, which is up to 60 scans per request.
CREATE TABLE local_food_alias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    -- Canonicalized the same way as local_food.canonical_name.
    alias VARCHAR(255) NOT NULL,
    local_food_id BIGINT NOT NULL,
    CONSTRAINT uk_local_food_alias UNIQUE (alias),
    CONSTRAINT fk_local_food_alias_food FOREIGN KEY (local_food_id) REFERENCES local_food (id) ON DELETE CASCADE
);

-- Unlike the user tables (see the handover on why foreign keys are not worth it
-- on H2 for those), the FK here is free: local_food_alias is only ever read by
-- an equality lookup on `alias`, which the unique constraint's own index serves.
-- There is no ORDER BY on this table for H2's auto-created FK index to disturb.
CREATE INDEX idx_local_food_alias_food ON local_food_alias (local_food_id);
