-- The workout feature: a fifth tab that plans, runs and records a daily session.
--
-- The app already knows the user's weight, goal and calorie budget and nothing
-- about how they move. These four tables close that half of the loop.
--
-- Sessions are generated from a curated catalogue (workout/exercises.csv), not
-- from the model. The model writes only the coaching prose, and coach_source
-- below records which path produced it -- so "the coach is down" degrades to a
-- missing sentence rather than a missing workout.

-- The six onboarding answers. One row per user; re-running onboarding updates it
-- in place rather than accumulating versions, because there is no screen that
-- shows you your old answers and a history nobody reads is a table nobody
-- maintains.
CREATE TABLE workout_profile (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    user_id BIGINT NOT NULL,
    -- Closed vocabularies, validated in WorkoutService before they get here.
    -- Deliberately NOT the same enum as users.goal: that one is about calories
    -- ('lose_weight' etc.) and this one is about training. They agree today and
    -- may not tomorrow; collapsing them would make the next divergence a
    -- migration instead of a value.
    goal VARCHAR(32) NOT NULL,
    level VARCHAR(32) NOT NULL,
    days_per_week INT NOT NULL,
    session_minutes INT NOT NULL,
    -- Comma-joined, and unlike local_food_alias that is the right call here:
    -- these are read only as part of loading the one row for the current user,
    -- never matched against. There is no query that would want an index.
    equipment VARCHAR(255) NOT NULL,
    preferences VARCHAR(255),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_workout_profile_user UNIQUE (user_id)
);

-- One planned session per user per calendar day.
--
-- The unique constraint is the feature, not bookkeeping: WorkoutService.today()
-- returns the existing row or generates one, so a user cannot re-roll today's
-- workout by pulling to refresh. Same principle as pinning a dish's first
-- nutrition resolution in nutrition_cache -- a plan that changes every time you
-- look at it is not a plan.
CREATE TABLE workout_session (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    user_id BIGINT NOT NULL,
    -- A local calendar date, not an instant: "today's workout" is a day in the
    -- user's timezone, and storing an instant would put the rollover at UTC
    -- midnight, which is 8am in Kuala Lumpur.
    session_date DATE NOT NULL,
    title VARCHAR(128) NOT NULL,
    focus VARCHAR(32) NOT NULL,
    -- Planned length. actual_minutes below is what it really took.
    minutes INT NOT NULL,
    level VARCHAR(32) NOT NULL,
    -- 'planned' | 'in_progress' | 'completed' | 'skipped'
    status VARCHAR(32) NOT NULL,
    -- The "Why this workout" text. CLOB rather than VARCHAR because it is model
    -- output: bounded by the prompt, but not by anything this schema enforces.
    coach_note CLOB,
    -- The bullets behind "What did you look at?", as a JSON array of strings.
    --
    -- Stored rather than recomputed on read, because they are part of the claim:
    -- the card says these are what today's session was built from, and rebuilding
    -- them next week off next week's data would quietly change what a past
    -- session says it was reasoning about. JSON in one column rather than a fifth
    -- table -- they are read only with their own session and never queried.
    coach_factors CLOB,
    -- 'ai' | 'rules'. Drives the "Standard plan" card in the UI, and is the only
    -- way to tell a deliberately plain note from a degraded one after the fact.
    coach_source VARCHAR(16),
    started_at TIMESTAMP,
    completed_at TIMESTAMP,
    actual_minutes INT,
    -- Post-session feedback, both optional. feel drives the next session's
    -- volume; energy is recorded for the analysis tab and nothing reads it yet.
    feel VARCHAR(32),
    energy VARCHAR(32),
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_workout_session_user_date UNIQUE (user_id, session_date)
);

-- The exercises of one session, frozen at generation time.
--
-- Name, target, sets, reps and cue are copied out of the catalogue rather than
-- referenced by key alone. A session is a record of what the user was actually
-- asked to do, and editing a row in exercises.csv must not silently rewrite
-- last month's history. exercise_key is kept alongside so the Replace sheet can
-- still find same-pattern alternatives.
CREATE TABLE workout_session_exercise (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    session_id BIGINT NOT NULL,
    position INT NOT NULL,
    exercise_key VARCHAR(64) NOT NULL,
    name VARCHAR(128) NOT NULL,
    target VARCHAR(128) NOT NULL,
    sets INT NOT NULL,
    reps INT NOT NULL,
    -- 'reps' | 'sec' | 'each_side' -- a plank prescribed as "30 reps" is wrong
    -- in a way no amount of number-tuning fixes.
    unit VARCHAR(16) NOT NULL,
    cue VARCHAR(512),
    -- Set when the user swapped this slot, holding the key they swapped away
    -- from. Without it there is no way to learn that push-ups get replaced by
    -- everyone -- the swap would look identical to never having been offered.
    replaced_from VARCHAR(64),
    CONSTRAINT uk_workout_exercise_slot UNIQUE (session_id, position)
);

-- One row per completed set.
--
-- The unique constraint is load-bearing for the offline story. Sets completed
-- without a connection are queued on the device and replayed on reconnect, and
-- a replay that arrives twice -- retry, double flush, two tabs -- must not count
-- the set twice. With this constraint the write is idempotent and the client is
-- free to be dumb about retries, which is the only kind of offline client that
-- actually works.
CREATE TABLE workout_set_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    session_id BIGINT NOT NULL,
    exercise_position INT NOT NULL,
    set_index INT NOT NULL,
    completed_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_workout_set_log UNIQUE (session_id, exercise_position, set_index)
);

-- No CREATE INDEX in this migration, deliberately -- every query shape these
-- tables have is already served by a unique constraint's own index:
--
--   "this user's recent sessions"   -> uk_workout_session_user_date leads on
--                                      user_id, then orders by session_date.
--   "everything for this session"   -> uk_workout_exercise_slot and
--                                      uk_workout_set_log both lead on
--                                      session_id.
--
-- V7 had to add indexes because those tables had none. Adding a second,
-- identical index here would cost every write and buy no read.
