-- Baseline: the schema as it existed under ddl-auto:update before Flyway was
-- introduced. On the live database this migration is never actually run —
-- spring.flyway.baseline-on-migrate marks V1 as already-applied instead,
-- since the tables already exist there. It exists so a fresh environment
-- (a new dev machine, a rebuilt VM) can reach the same schema from empty.
-- Column/table names and constraints below were captured from the live
-- database via `SCRIPT NODATA`, not guessed from the entity classes.

CREATE TABLE app_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    age INTEGER,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    daily_budget INTEGER,
    email VARCHAR(255),
    exercise_frequency VARCHAR(255),
    google_sub VARCHAR(255) NOT NULL,
    height_cm DOUBLE PRECISION,
    name VARCHAR(255),
    picture_url VARCHAR(1024),
    sex VARCHAR(255),
    steps INTEGER,
    weight_kg DOUBLE PRECISION,
    goal VARCHAR(255),
    water_target_ml INTEGER,
    CONSTRAINT uk_app_user_google_sub UNIQUE (google_sub)
);

CREATE TABLE meal_analysis (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    calories DOUBLE PRECISION NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    grade VARCHAR(2) NOT NULL,
    result_json CLOB,
    score INTEGER NOT NULL,
    summary VARCHAR(512),
    thumbnail CLOB,
    user_id BIGINT,
    source VARCHAR(255)
);

CREATE TABLE water_entry (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    date DATE NOT NULL,
    total_ml INTEGER NOT NULL,
    user_id BIGINT NOT NULL
);

CREATE TABLE weight_entry (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    logged_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    user_id BIGINT NOT NULL,
    weight_kg DOUBLE PRECISION NOT NULL
);
