-- Persisted menu-tier scans (signed-in users only; visitors get an ephemeral
-- response that is never written here — see MenuRankingService).

CREATE TABLE menu_scan (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    user_id BIGINT NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    dish_count INTEGER NOT NULL,
    truncated BOOLEAN NOT NULL,
    summary VARCHAR(512),
    thumbnail CLOB,
    result_json CLOB
);
