-- Resolved-nutrition memo, keyed by a canonicalized dish name, so the same dish
-- always resolves to the same numbers instead of re-rolling the USDA lookup /
-- model-estimate lottery on every scan (see NutritionCacheService).
--
-- Global, not per-user: nutrition facts for "char kway teow" don't depend on
-- who photographed it. Deleting a row simply re-resolves that dish on the next
-- scan, which is the intended way to correct a bad entry.

CREATE TABLE nutrition_cache (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    canonical_name VARCHAR(255) NOT NULL,
    display_name VARCHAR(255) NOT NULL,
    resolved_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    source VARCHAR(32) NOT NULL,
    food_group VARCHAR(64),
    fried BOOLEAN NOT NULL,
    confidence DOUBLE PRECISION NOT NULL,
    grams DOUBLE PRECISION NOT NULL,
    portion VARCHAR(255),
    calories_per100g DOUBLE PRECISION NOT NULL,
    protein_per100g DOUBLE PRECISION NOT NULL,
    carbs_per100g DOUBLE PRECISION NOT NULL,
    fat_per100g DOUBLE PRECISION NOT NULL,
    fiber_per100g DOUBLE PRECISION NOT NULL,
    sugar_per100g DOUBLE PRECISION NOT NULL,
    sodium_per100g DOUBLE PRECISION NOT NULL,
    CONSTRAINT uk_nutrition_cache_canonical_name UNIQUE (canonical_name)
);
