// Shown once, right after login, when today's dashboard has no meals logged yet.
// One joke/CTA array per supported language — picked randomly by the caller.
export const EMPTY_STATE_JOKES = {
  en: [
    { message: 'No meals logged today… either you’re fasting or your stomach lost its login access.', cta: '🔑 Log My Stomach Back In' },
    { message: 'Your food tracker is empty. Your body, however, strongly disagrees.', cta: '🍔 Settle the Argument' },
    { message: 'No data found. Either you didn’t eat… or the evidence has been deleted.', cta: '📸 Submit the Evidence' },
    { message: '0 meals recorded. That’s impressive… or deeply concerning.', cta: "🥲 Prove I'm Alive ⭐" },
    { message: 'No entries found. We’re starting to suspect you’re powered by sunlight.', cta: "☀️ I'm Actually Human" },
    { message: 'Your meals are so private… even our AI couldn’t find them.', cta: '🤫 Reveal My Lunch' },
    { message: 'No meals today. Don’t worry, we’ll notify next of kin if this continues.', cta: '🍜 Cancel the Funeral 😭' },
    { message: 'No meals logged. Don’t worry — your survival is currently unverified.', cta: '💀 Verify My Survival' },
    { message: '0 meals today. That’s either discipline or denial.', cta: '😅 Fine, I Ate' },
    { message: 'No food records. We’re not saying you didn’t eat… but the evidence says otherwise.', cta: '📷 Present the Evidence' },
    { message: 'Nothing here. If this continues, we may need to notify your refrigerator.', cta: '🧊 Save My Fridge' },
    { message: 'Your plate is empty in the system… and probably in real life too.', cta: '🍽️ Fix This Situation' },
    { message: 'No meals yet today… your dashboard is feeling a bit hungry too.', cta: '🍱 Feed Us Both' },
    { message: 'Still empty. Go eat something so I have something to judge 😄', cta: '😤 Judge This Meal' },
  ],
  zh: [
    { message: '今天还没有记录任何一餐……不是在断食，就是你的胃“账号”被登出了。', cta: '🔑 帮我的胃重新登录' },
    { message: '你的饮食记录是空的，但你的身体强烈不同意这一点。', cta: '🍔 平息这场争论' },
    { message: '找不到任何数据。要么你没吃东西，要么证据已被删除。', cta: '📸 提交证据' },
    { message: '记录了 0 餐。这要么很厉害，要么很令人担心。', cta: '🥲 证明我还活着 ⭐' },
    { message: '找不到任何记录。我们开始怀疑你是靠光合作用维生的。', cta: '☀️ 我其实是人类' },
    { message: '你的三餐太私密了……连我们的 AI 都找不到。', cta: '🤫 揭露我的午餐' },
    { message: '今天没有记录。别担心，如果一直这样，我们会通知你的家属。', cta: '🍜 取消葬礼安排 😭' },
    { message: '没有任何记录。别担心 — 你的生存状态目前尚未验证。', cta: '💀 验证我还活着' },
    { message: '今天记录了 0 餐。这要么是自律，要么是逃避现实。', cta: '😅 好吧，我吃了' },
    { message: '没有任何饮食记录。我们不是说你没吃……但证据可不这么说。', cta: '📷 提交证据' },
    { message: '这里什么都没有。再这样下去，我们可能得通知你家冰箱了。', cta: '🧊 拯救我的冰箱' },
    { message: '系统里你的餐盘是空的……现实生活中大概也是。', cta: '🍽️ 立刻解决这个问题' },
    { message: '今天还没有记录……连仪表板都有点饿了。', cta: '🍱 一起喂饱我们吧' },
    { message: '还是空的。去吃点东西吧，这样我才有东西可以评分 😄', cta: '😤 来评一评这餐' },
  ],
  ms: [
    { message: 'Tiada makanan direkod hari ini… sama ada anda berpuasa atau perut anda hilang akses log masuk.', cta: '🔑 Log Masuk Semula Perut Saya' },
    { message: 'Penjejak makanan anda kosong. Namun, badan anda sangat tidak bersetuju.', cta: '🍔 Selesaikan Perdebatan Ini' },
    { message: 'Tiada data dijumpai. Sama ada anda tidak makan… atau bukti telah dipadam.', cta: '📸 Serahkan Bukti' },
    { message: '0 makanan direkod. Itu mengagumkan… atau agak membimbangkan.', cta: '🥲 Buktikan Saya Masih Hidup ⭐' },
    { message: 'Tiada entri dijumpai. Kami mula syak anda hidup dengan tenaga suria.', cta: '☀️ Saya Sebenarnya Manusia' },
    { message: 'Makanan anda begitu peribadi… AI kami pun tak jumpa.', cta: '🤫 Dedahkan Makan Tengah Hari Saya' },
    { message: 'Tiada makanan hari ini. Jangan risau, kami akan maklumkan waris jika ini berterusan.', cta: '🍜 Batalkan Pengebumian 😭' },
    { message: 'Tiada makanan direkod. Jangan risau — status hidup anda belum disahkan.', cta: '💀 Sahkan Saya Masih Hidup' },
    { message: '0 makanan hari ini. Itu sama ada disiplin atau penafian.', cta: '😅 Baiklah, Saya Dah Makan' },
    { message: 'Tiada rekod makanan. Kami tidak kata anda tak makan… tapi bukti mengatakan sebaliknya.', cta: '📷 Kemukakan Bukti' },
    { message: 'Tiada apa-apa di sini. Jika ini berterusan, kami mungkin perlu maklumkan peti sejuk anda.', cta: '🧊 Selamatkan Peti Sejuk Saya' },
    { message: 'Pinggan anda kosong dalam sistem… mungkin dalam kehidupan sebenar juga.', cta: '🍽️ Betulkan Keadaan Ini' },
    { message: 'Masih belum ada makanan hari ini… papan pemuka anda pun rasa lapar.', cta: '🍱 Beri Kami Berdua Makan' },
    { message: 'Masih kosong. Pergi makan sesuatu supaya saya ada bahan untuk dinilai 😄', cta: '😤 Nilai Makanan Ini' },
  ],
}
